import {signupStatus} from '@/lib/server/platform';
import {requireAdmin,createAdminSession,adminCookie,logoutAdmin} from '@/lib/server/admin-auth';
import {isPlatformAdmin,requirePlatformAdmin,setupStatus,savePlatform,platformConfig} from '@/lib/server/platform';
import {beginSignup,completeSignup} from '@/lib/server/embedded-signup';
import {compileColumns,type ImportColumn} from '@/lib/import-mapping';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {all,one,run,id,now,transaction} from '@/lib/server/store';
import {ApiError,user,publicProfile,csrf,body,required,register,limitAuth,checkPassword,loginSession,sessionCookie,logout} from '@/lib/server/auth';
import {connection,encrypt,decrypt,meta,templates} from '@/lib/server/whatsapp';
import {normalizePhone,stages,rowsToLeads,parseCSV,sheetExportURL,canFreeform,type Lead,type Knowledge} from '@/lib/crm';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
function clean(value:unknown,max=3000){if(value===undefined||value===null)return '';if(typeof value!=='string')throw new ApiError(400,'Expected text.');if(value.length>max)throw new ApiError(400,'This value is too long.');return value.trim();}
function customFields(value:unknown):Record<string,string>{if(value===undefined)return {};if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length>40)throw new ApiError(400,'Use up to 40 custom fields.');return Object.fromEntries(Object.entries(value).map(([key,value])=>[required(key,'Field name',80),clean(value,5000)]));}
function validLead(data:Record<string,unknown>){let phone;try{phone=normalizePhone(required(data.phone,'Phone'));}catch(e){throw new ApiError(400,(e as Error).message);}const name=required(data.name,'Name'),email=clean(data.email,200);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new ApiError(400,'Enter a valid email.');const stage=clean(data.stage)||'New';if(!stages.includes(stage as typeof stages[number]))throw new ApiError(400,'Choose a valid lead stage.');const consent=data.consent===true||data.consent===1?1:0;const consentNote=clean(data.consentNote,500);if(consent&&!consentNote)throw new ApiError(400,'Record when or how this lead gave WhatsApp permission.');return {customFields:customFields(data.customFields),name,phone,email,stage,consent,consentNote,company:clean(data.company,200),notes:clean(data.notes,5000)};}
function insertLead(uid:string,d:Omit<ReturnType<typeof validLead>,'customFields'>&{customFields?:Record<string,string>},source:string){const leadId=id();run('INSERT INTO leads(id,userId,name,phone,email,company,stage,source,notes,consent,consentNote,createdAt,customFields) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',leadId,uid,d.name,d.phone,d.email,d.company,d.stage,source,d.notes,d.consent,d.consentNote,now(),JSON.stringify(d.customFields||{}));return leadId;}
async function dispatch(req:Request,context:{params:Promise<{path:string[]}>}){
 const {path}=await context.params;const route=path.join('/'),method=req.method;
 if(route==='webhooks/whatsapp')return webhook(req);
 if(method!=='GET')csrf(req);
 if(route==='admin/login'&&method==='POST'){const d=await body(req);limitAuth('platform-admin-login');if(d.username!=='admin')throw new ApiError(401,'Username or password is incorrect.');const token=createAdminSession(required(d.password,'Password'));run('DELETE FROM auth_attempts WHERE email=?','platform-admin-login');return json({ok:true},200,{'Set-Cookie':adminCookie(token)});}
 if(route==='admin/logout'&&method==='POST'){logoutAdmin(req);return json({ok:true},200,{'Set-Cookie':adminCookie('')});}
 if(route==='admin/session'&&method==='GET'){try{requireAdmin(req);return json({authenticated:true});}catch{return json({authenticated:false});}}
 if(route==='platform/progress'&&method==='GET'){requireAdmin(req);const row=one<{value:string}>('SELECT value FROM platform_settings WHERE id=?','meta-progress');const progress=row?JSON.parse(row.value):null;return json({progress:progress?.appId===platformConfig().appId?progress:null});}
 if(route==='platform/whatsapp'){requireAdmin(req);if(method==='GET')return json(setupStatus());if(method==='POST'){savePlatform(await body(req));return json(setupStatus());}}
 if(route==='admin/test-whatsapp'){
  requireAdmin(req);
  if(method==='GET')return json({available:process.env.LOCAL_DEVELOPMENT==='true'});
  if(process.env.LOCAL_DEVELOPMENT!=='true')throw new ApiError(403,'Test connections are available only in local development.');
  if(method!=='POST')throw new ApiError(405,'Method not allowed.');
  const d=await body(req),target=required(d.userId,'Workspace'),phoneId=required(d.phoneId,'Phone number ID'),wabaId=required(d.wabaId,'WhatsApp account ID'),token=required(d.token,'Access token',4000);
  if(!one('SELECT id FROM users WHERE id=?',target)||isPlatformAdmin(target))throw new ApiError(404,'Choose an existing client workspace.');
  if(!/^\d+$/.test(phoneId)||!/^\d+$/.test(wabaId))throw new ApiError(400,'Meta account IDs contain only digits.');
  if(connection(target)&&connection(target)?.phoneId!==phoneId)throw new ApiError(409,'This workspace already has a different number connected.');
  if(one('SELECT userId FROM connections WHERE phoneId=? AND userId<>?',phoneId,target))throw new ApiError(409,'This number belongs to another workspace.');
  const numbers=await meta(`${wabaId}/phone_numbers?fields=id,display_phone_number&limit=100`,token);
  const phone=numbers.data?.find(p=>p.id===phoneId);if(!phone)throw new ApiError(400,'The token cannot access this account and number. Check the IDs from Meta.');
  transaction(()=>{
   if(one('SELECT userId FROM connections WHERE phoneId=? AND userId<>?',phoneId,target))throw new ApiError(409,'This number belongs to another workspace.');
   const existing=connection(target);if(existing&&existing.phoneId!==phoneId)throw new ApiError(409,'A different number was connected during setup.');
   run('INSERT INTO connections(userId,phoneId,wabaId,displayPhone,token,updatedAt,status) VALUES(?,?,?,?,?,?,?) ON CONFLICT(userId) DO UPDATE SET token=excluded.token,wabaId=excluded.wabaId,displayPhone=excluded.displayPhone,updatedAt=excluded.updatedAt,status=excluded.status',target,phoneId,wabaId,phone.display_phone_number,encrypt(token),now(),'pending');
  });
  await meta(`${wabaId}/subscribed_apps`,token,{method:'POST',body:'{}'});
  run("UPDATE connections SET status='connected',updatedAt=? WHERE userId=? AND phoneId=?",now(),target,phoneId);
  return json({ok:true});
 }
 if(route==='admin/clients'&&method==='GET'){requireAdmin(req);const clients=all<{id:string}>(`SELECT u.id,u.name,u.email,u.business,u.createdAt,(SELECT COUNT(*) FROM leads l WHERE l.userId=u.id) AS leadCount,(SELECT COUNT(*) FROM messages m WHERE m.userId=u.id) AS messageCount,(SELECT COUNT(*) FROM knowledge k WHERE k.userId=u.id) AS knowledgeCount,c.displayPhone,c.status AS connectionStatus FROM users u LEFT JOIN connections c ON c.userId=u.id WHERE u.id<>'platform-admin' ORDER BY u.createdAt DESC`).filter(u=>!isPlatformAdmin(u.id));return json({clients,setupReady:setupStatus().ready});}
 if(route==='auth'&&method==='GET'){try{return json({...(()=>{const u=user(req);return isPlatformAdmin(u.id)?{user:null,redirectTo:'/admin'}:{user:publicProfile(u)};})()});}catch{return json({user:null});}}
 if(route==='auth/register'&&method==='POST'){const d=await body(req);limitAuth(String(d.email||'').toLowerCase());const uid=register(d);return json({ok:true},201,{'Set-Cookie':sessionCookie(loginSession(uid))});}
 if(route==='auth/login'&&method==='POST'){const d=await body(req),email=required(d.email,'Email').toLowerCase();limitAuth(email);if(email==='admin')throw new ApiError(403,'Use /admin to sign in as superadmin.');const row=one<{id:string;password:string}>('SELECT id,password FROM users WHERE email=?',email);if(!row||!checkPassword(required(d.password,'Password'),row.password))throw new ApiError(401,'Email or password is incorrect.');run('DELETE FROM auth_attempts WHERE email=?',email);return json({ok:true},200,{'Set-Cookie':sessionCookie(loginSession(row.id))});}
 if(route==='auth/logout'&&method==='POST'){logout(req);return json({ok:true},200,{'Set-Cookie':sessionCookie('')});}
 const u=user(req),uid=u.id;if(isPlatformAdmin(uid))throw new ApiError(403,'Use the separate administration console at /admin.');
 if(route==='whatsapp/signup/config'&&method==='GET'){const s=signupStatus(uid);return json({ready:s.ready,testMode:s.testMode,...(s.ready?{appId:s.appId,configId:s.configId,version:process.env.META_GRAPH_VERSION||'v25.0'}:{})});}
 if(route==='whatsapp/signup/start'&&method==='POST')return json(beginSignup(req,uid));
 if(route==='whatsapp/signup/complete'&&method==='POST')return json(await completeSignup(req,uid,await body(req)));
 if(route==='workspace'&&method==='GET'){const c=connection(uid);return json({profile:{...publicProfile(u),isPlatformAdmin:isPlatformAdmin(uid)},leads:all<Omit<Lead,'customFields'>&{customFields:string}>('SELECT * FROM leads WHERE userId=? ORDER BY createdAt DESC',uid).map(l=>({...l,customFields:JSON.parse(l.customFields)})),knowledge:all('SELECT * FROM knowledge WHERE userId=? ORDER BY updatedAt DESC',uid),messages:all('SELECT * FROM (SELECT * FROM messages WHERE userId=? ORDER BY createdAt DESC LIMIT 5000) ORDER BY createdAt ASC',uid),connection:c?{phoneId:c.phoneId,wabaId:c.wabaId,displayPhone:c.displayPhone,status:c.status}:null});}
 if(route==='profile'&&method==='PATCH'){const d=await body(req),name=required(d.name,'Name'),business=required(d.business,'Business name'),color=clean(d.brandColor)||'#087b66',logo=clean(d.logo,400000);if(!/^#[a-fA-F0-9]{6}$/.test(color))throw new ApiError(400,'Choose a valid brand color.');if(logo&&!/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(logo))throw new ApiError(400,'Upload a PNG, JPEG, or WebP logo.');run('UPDATE users SET name=?,business=?,brandColor=?,logo=?,supportEmail=?,hours=?,assistantName=?,assistantTone=?,welcome=?,assistantActive=? WHERE id=?',name,business,color,logo,clean(d.supportEmail,200),clean(d.hours,500),clean(d.assistantName,100),clean(d.assistantTone,100),clean(d.welcome,1000),d.assistantActive?1:0,uid);return json({ok:true});}
 if(route==='leads'&&method==='POST'){const d=validLead(await body(req));if(one('SELECT id FROM leads WHERE userId=? AND phone=?',uid,d.phone))throw new ApiError(409,'A lead with this WhatsApp number already exists.');return json({id:insertLead(uid,d,'Manual')},201);}
 if(path[0]==='leads'&&path.length===2&&method==='PATCH'){if(!one('SELECT id FROM leads WHERE id=? AND userId=?',path[1],uid))throw new ApiError(404,'Lead not found.');const d=validLead(await body(req));if(one('SELECT id FROM leads WHERE phone=? AND userId=? AND id<>?',d.phone,uid,path[1]))throw new ApiError(409,'This phone number belongs to another lead.');run('UPDATE leads SET name=?,phone=?,email=?,company=?,stage=?,notes=?,consent=?,consentNote=?,customFields=? WHERE id=? AND userId=?',d.name,d.phone,d.email,d.company,d.stage,d.notes,d.consent,d.consentNote,JSON.stringify(d.customFields),path[1],uid);return json({ok:true});}
 if(route==='imports/sheet'&&method==='POST'){const d=await body(req);let url:string;try{url=sheetExportURL(required(d.url,'Google Sheets URL',2000));}catch(e){throw new ApiError(400,(e as Error).message);}let response=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(15000)});for(let i=0;i<3&&response.status>=300&&response.status<400;i++){const location=response.headers.get('location');if(!location)break;const next:URL=new URL(location,url);if(next.protocol!=='https:'||!(next.hostname==='docs.google.com'||next.hostname.endsWith('.googleusercontent.com')))throw new ApiError(400,'This sheet requires Google sign-in. Download it as CSV or paste its rows instead.');response=await fetch(next,{redirect:'manual',signal:AbortSignal.timeout(15000)});url=next.href;}if(!response.ok||response.headers.get('content-type')?.includes('text/html'))throw new ApiError(400,'This sheet is private or unavailable. Keep it private: download CSV or copy and paste its rows.');if(Number(response.headers.get('content-length')||0)>2_000_000)throw new ApiError(413,'Sheet exceeds 2 MB.');const reader=response.body?.getReader();let text='';if(reader){const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true});if(text.length>2_000_000){await reader.cancel();throw new ApiError(413,'Sheet exceeds 2 MB.');}}}return json({rows:parseCSV(text)});}
 if(route==='imports'&&method==='POST'){const d=await body(req);if(!Array.isArray(d.rows)||d.rows.length>1000||!d.rows.every((r:unknown)=>Array.isArray(r)&&r.length<=100&&r.every(c=>typeof c==='string')))throw new ApiError(400,'Import up to 1,000 valid rows.');let custom:{label:string;column:number}[]=[];if(d.columns!==undefined){let compiled;try{compiled=compileColumns(d.columns as ImportColumn[],Math.max(Number.isInteger(d.columnCount)&&d.columnCount>=0&&d.columnCount<=100?d.columnCount:0,...d.rows.map((r:string[])=>r.length)));}catch{throw new ApiError(400,'Choose valid fields.');}if(compiled.errors.length)throw new ApiError(400,compiled.errors.join(' '));d.mapping=compiled.mapping;custom=compiled.custom;}if(!d.mapping||!['name','phone'].every(f=>Number.isInteger(d.mapping[f])&&d.mapping[f]>=0))throw new ApiError(400,'Map the name and phone columns.');const source=d.source==='Google Sheets'?'Google Sheets':'CSV';const parsed=rowsToLeads(d.rows,d.mapping,source,custom);if(!d.confirm)return json({preview:parsed.valid.slice(0,5),valid:parsed.valid.length,errors:parsed.errors,duplicates:parsed.duplicates});if(!parsed.valid.length)throw new ApiError(400,'No valid leads were found. Review the skipped-row report.');let imported=0,duplicates=parsed.duplicates;transaction(()=>{for(const row of parsed.valid){const lead=validLead(row);if(one('SELECT id FROM leads WHERE userId=? AND phone=?',uid,lead.phone)){duplicates++;continue;}insertLead(uid,lead,source);imported++;}});return json({imported,duplicates,skipped:parsed.errors.length,errors:parsed.errors});}
 if(route==='knowledge'&&method==='POST'){const d=await body(req);run('INSERT INTO knowledge(id,userId,title,body,updatedAt) VALUES(?,?,?,?,?)',id(),uid,required(d.title,'Title'),required(d.body,'Information',50000),now());return json({ok:true},201);}
 if(path[0]==='knowledge'&&path.length===2&&(method==='PATCH'||method==='DELETE')){if(!one('SELECT id FROM knowledge WHERE id=? AND userId=?',path[1],uid))throw new ApiError(404,'Information not found.');if(method==='DELETE')run('DELETE FROM knowledge WHERE id=? AND userId=?',path[1],uid);else{const d=await body(req);run('UPDATE knowledge SET title=?,body=?,updatedAt=? WHERE id=? AND userId=?',required(d.title,'Title'),required(d.body,'Information',50000),now(),path[1],uid);}return json({ok:true});}
 if(route==='knowledge/search'&&method==='POST'){const d=await body(req),q=required(d.question,'Question',1000).toLowerCase(),words=q.match(/[\p{L}\p{N}]{3,}/gu)||[];const docs=all<Knowledge>('SELECT * FROM knowledge WHERE userId=?',uid);const found=docs.map(doc=>({doc,score:words.filter(w=>(doc.title+' '+doc.body).toLowerCase().includes(w)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);return json({matches:found.map(x=>x.doc),mode:'knowledge-search'});}
 if(route==='whatsapp'&&method==='POST'){requirePlatformAdmin(uid);const d=await body(req),phoneId=required(d.phoneId,'Phone number ID'),wabaId=required(d.wabaId,'WhatsApp account ID'),token=required(d.token,'Access token',4000);if(!/^\d+$/.test(phoneId)||!/^\d+$/.test(wabaId))throw new ApiError(400,'Meta account IDs contain only digits.');const numbers=await meta(`${wabaId}/phone_numbers?fields=id,display_phone_number&limit=100`,token);const phone=numbers.data?.find((p:{id:string})=>p.id===phoneId);if(!phone)throw new ApiError(400,'This phone number does not belong to the selected WhatsApp account.');if(one('SELECT userId FROM connections WHERE phoneId=? AND userId<>?',phoneId,uid))throw new ApiError(409,'That number is already connected to another workspace.');run('INSERT INTO connections(userId,phoneId,wabaId,displayPhone,token,updatedAt) VALUES(?,?,?,?,?,?) ON CONFLICT(userId) DO UPDATE SET phoneId=excluded.phoneId,wabaId=excluded.wabaId,displayPhone=excluded.displayPhone,token=excluded.token,updatedAt=excluded.updatedAt',uid,phoneId,wabaId,phone.display_phone_number,encrypt(token),now());return json({ok:true});}
 if(route==='whatsapp/templates'&&method==='GET')return json({templates:await templates(uid)});
 if(route==='messages'&&method==='POST'){const d=await body(req),leadId=required(d.leadId,'Lead'),requestKey=required(d.requestKey,'Message reference');const lead=one<Lead>('SELECT * FROM leads WHERE id=? AND userId=?',leadId,uid);if(!lead)throw new ApiError(404,'Lead not found.');if(!lead.consent)throw new ApiError(400,'Record this lead’s WhatsApp permission before starting a chat.');const c=connection(uid);if(c?.status==='pending')throw new ApiError(409,'Finish connecting WhatsApp before sending messages.');if(!c)throw new ApiError(409,'Connect your WhatsApp business number before sending.');const existing=one('SELECT * FROM messages WHERE userId=? AND requestKey=?',uid,requestKey);if(existing){if(['accepted','sent','delivered','read'].includes(String(existing.status)))return json({message:existing});throw new ApiError(409,'This message was already attempted. Check its delivery status before creating another.');}let payload:Record<string,unknown>,messageText:string,templateName:string|null=null;
 if(d.template){const approved=(await templates(uid)).find(t=>t.name===d.template&&t.language===d.language);if(!approved)throw new ApiError(400,'Select an approved text template.');const variables=Array.isArray(d.variables)?d.variables.map((v:unknown)=>required(v,'Template value',500)):[];if(variables.length!==approved.parameters)throw new ApiError(400,'Fill in every template value.');messageText=approved.body.replace(/\{\{(\d+)\}\}/g,(_,n)=>variables[Number(n)-1]||'');templateName=approved.name;payload={type:'template',template:{name:approved.name,language:{code:approved.language},...(variables.length?{components:[{type:'body',parameters:variables.map((text:string)=>({type:'text',text}))}]}:{})}};
 }else{if(!canFreeform(lead))throw new ApiError(400,'Start with an approved template. Free-text replies become available for 24 hours after the lead messages you.');messageText=required(d.body,'Message',4000);payload={type:'text',text:{body:messageText}};}
 const messageId=id();run('INSERT INTO messages(id,userId,leadId,direction,body,status,template,requestKey,createdAt) VALUES(?,?,?,?,?,?,?,?,?)',messageId,uid,leadId,'outbound',messageText,'sending',templateName,requestKey,now());
 try{const result=await meta(`${c.phoneId}/messages`,decrypt(c.token),{method:'POST',body:JSON.stringify({messaging_product:'whatsapp',to:lead.phone.replace('+',''),...payload})});if(!result.messages?.[0]?.id)throw new Error('Missing delivery reference');run('UPDATE messages SET status=?,metaId=? WHERE id=?','accepted',result.messages[0].id,messageId);run("UPDATE leads SET stage=CASE WHEN stage='New' THEN 'Contacted' ELSE stage END WHERE id=? AND userId=?",leadId,uid);}catch{run('UPDATE messages SET status=?,error=? WHERE id=?','unconfirmed','Delivery was not confirmed. Check WhatsApp before trying again.',messageId);throw new ApiError(502,'Delivery was not confirmed. Check the conversation before retrying to avoid duplicates.');}return json({ok:true,messageId});}
 throw new ApiError(404,'This action is not available.');
}
async function webhook(req:Request){
 if(req.method==='GET'){
  const p=new URL(req.url).searchParams,configured=platformConfig().verifyToken;
  const tokenMatches=!!configured&&p.get('hub.verify_token')===configured;
  const validMode=p.get('hub.mode')==='subscribe',hasChallenge=p.has('hub.challenge');
  const accepted=tokenMatches&&validMode&&hasChallenge;
  // Never log URLs, tokens, challenge values, headers or sender details.
  console.info('WhatsApp webhook verification',JSON.stringify({at:new Date().toISOString(),tokenConfigured:!!configured,tokenProvided:p.has('hub.verify_token'),tokenMatches,validMode,hasChallenge,status:accepted?200:403}));
  if(accepted)return new Response(p.get('hub.challenge'),{headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});
  throw new ApiError(403,'Verification failed.');
 }
 if(req.method!=='POST')throw new ApiError(405,'Method not allowed.');if(!platformConfig().appSecret)throw new ApiError(503,'Webhook is not configured.');const raw=await req.text(),expected='sha256='+createHmac('sha256',platformConfig().appSecret).update(raw).digest('hex'),signature=req.headers.get('x-hub-signature-256')||'';if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))throw new ApiError(403,'Invalid webhook signature.');const data=JSON.parse(raw);
 for(const entry of data.entry||[])for(const change of entry.changes||[]){const v=change.value;const c=one<{userId:string}>('SELECT userId FROM connections WHERE phoneId=?',String(v?.metadata?.phone_number_id||''));if(!c)continue;for(const s of v.statuses||[]){const ranks:Record<string,number>={accepted:0,sent:1,delivered:2,read:3,failed:4};const current=one<{status:string}>('SELECT status FROM messages WHERE metaId=? AND userId=?',s.id,c.userId);if(current&&ranks[s.status]!==undefined&&ranks[s.status]>=(ranks[current.status]??-1))run('UPDATE messages SET status=? WHERE metaId=? AND userId=?',s.status,s.id,c.userId);}
 for(const m of v.messages||[]){if(one('SELECT id FROM messages WHERE metaId=?',m.id))continue;const phone=normalizePhone(m.from);transaction(()=>{let lead=one<Lead>('SELECT * FROM leads WHERE userId=? AND phone=?',c.userId,phone);if(!lead){const name=v.contacts?.find((p:{wa_id:string})=>p.wa_id===m.from)?.profile?.name||phone;const leadId=insertLead(c.userId,{name,phone,email:'',company:'',stage:'New',notes:'',consent:0,consentNote:''},'WhatsApp');lead=one<Lead>('SELECT * FROM leads WHERE id=?',leadId)!;}const timestamp=new Date(Number(m.timestamp)*1000).toISOString();run('UPDATE leads SET lastInboundAt=CASE WHEN lastInboundAt IS NULL OR lastInboundAt<? THEN ? ELSE lastInboundAt END WHERE id=?',timestamp,timestamp,lead.id);run('INSERT OR IGNORE INTO messages(id,userId,leadId,direction,body,status,metaId,createdAt) VALUES(?,?,?,?,?,?,?,?)',id(),c.userId,lead.id,'inbound',m.text?.body||`[${m.type} message]`,'received',m.id,timestamp);});}}
 return json({received:true});
}
async function handler(req:Request,ctx:{params:Promise<{path:string[]}>}){try{return await dispatch(req,ctx);}catch(e){if(e instanceof ApiError)return json({error:e.message},e.status);console.error('CRM request failed:',e instanceof Error?e.message:'Unknown error');return json({error:'Something went wrong. Your changes were not completed. Please try again.'},500);}}
export {handler as GET,handler as POST,handler as PATCH,handler as DELETE};
