import {hasSignupTestAccess} from '../signup-test-access';
import {one,run,now} from './store';
import {encrypt,decrypt} from './whatsapp';
import {ApiError} from './auth';
export function isPlatformAdmin(id:string){return (id==='platform-admin'&&!!process.env.ADMIN_PASSWORD)||(process.env.PLATFORM_ADMIN_USER_IDS||'').split(',').map(s=>s.trim()).filter(Boolean).includes(id);}
export function requirePlatformAdmin(id:string){if(!isPlatformAdmin(id))throw new ApiError(403,'Only the platform administrator can manage this setup.');}
export type PlatformConfig={appId:string;configId:string;appSecret:string;verifyToken:string;enabled:boolean};
export function platformConfig():PlatformConfig{const saved=one<{value:string}>('SELECT value FROM platform_settings WHERE id=?','meta');return saved?JSON.parse(decrypt(saved.value)):{appId:process.env.META_APP_ID||'',configId:process.env.META_SIGNUP_CONFIG_ID||'',appSecret:process.env.META_APP_SECRET||'',verifyToken:process.env.META_VERIFY_TOKEN||'',enabled:process.env.META_ONBOARDING_ENABLED==='true'};}
export function setupStatus(){const c=platformConfig();let publicUrl=false;try{const u=new URL(process.env.APP_URL||'');publicUrl=u.protocol==='https:'&&!/localhost|\.test$|\.local$|^127\.|^192\.168\.|^10\.|^\[/.test(u.hostname);}catch{}const checks=[{label:'Meta application ID',done:/^\d+$/.test(c.appId)},{label:'Embedded Signup configuration ID',done:/^\d+$/.test(c.configId)},{label:'Meta app secret',done:!!c.appSecret},{label:'Webhook verification token',done:!!c.verifyToken},{label:'Public HTTPS portal address',done:publicUrl},{label:'Meta permissions approved and webhook configured (administrator confirmation)',done:c.enabled}];return {ready:checks.every(c=>c.done),checks,appId:c.appId,configId:c.configId,enabled:c.enabled,hasAppSecret:!!c.appSecret,hasVerifyToken:!!c.verifyToken,webhookUrl:(process.env.APP_URL||'').replace(/\/$/,'')+'/api/webhooks/whatsapp'};}
export function savePlatform(d:Record<string,unknown>){const previous=platformConfig();const appId=String(d.appId||'').trim(),configId=String(d.configId||'').trim();if(!/^\d+$/.test(appId)||!/^\d+$/.test(configId))throw new ApiError(400,'Enter numeric Meta application and signup configuration IDs.');const appSecret=typeof d.appSecret==='string'&&d.appSecret.trim()?d.appSecret.trim():previous.appSecret,verifyToken=typeof d.verifyToken==='string'&&d.verifyToken.trim()?d.verifyToken.trim():previous.verifyToken;if(appSecret.length>4000||verifyToken.length>4000)throw new ApiError(400,'Credential is too long.');run('INSERT INTO platform_settings(id,value,updatedAt) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value,updatedAt=excluded.updatedAt','meta',encrypt(JSON.stringify({appId,configId,appSecret,verifyToken,enabled:d.enabled===true})),now());}

export function signupStatus(userId:string){const s=setupStatus();const testMode=!s.ready&&hasSignupTestAccess(userId,process.env);return {...s,testMode,ready:s.ready||(testMode&&s.checks.slice(0,-1).every(check=>check.done))};}
