import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {one} from './store';
import {ApiError} from './auth';
import type {Template} from '../crm';
type Connection={status:string;userId:string;phoneId:string;wabaId:string;displayPhone:string;token:string};
function key(){const configured=process.env.CREDENTIAL_ENCRYPTION_KEY;if(configured){const value=Buffer.from(configured,'hex');if(value.length!==32)throw new Error('Credential key must be 32 bytes.');return value;}if(process.env.NODE_ENV==='production'&&process.env.LOCAL_DEVELOPMENT!=='true')throw new ApiError(503,'Credential encryption must be configured before connecting WhatsApp.');const p=resolve('data/credential.key');mkdirSync(resolve('data'),{recursive:true,mode:0o700});if(!existsSync(p))writeFileSync(p,randomBytes(32),{mode:0o600,flag:'wx'});return readFileSync(p);}
export function encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);return Buffer.concat([iv,cipher.update(value),cipher.final(),cipher.getAuthTag()]).toString('base64');}
export function decrypt(value:string){const b=Buffer.from(value,'base64'),cipher=createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));cipher.setAuthTag(b.subarray(-16));return Buffer.concat([cipher.update(b.subarray(12,-16)),cipher.final()]).toString();}
export function connection(userId:string){return one<Connection>('SELECT * FROM connections WHERE userId=?',userId);}
export async function meta(path:string,token:string,options:RequestInit={}){const version=process.env.META_GRAPH_VERSION||'v25.0';const response=await fetch(`https://graph.facebook.com/${version}/${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),cache:'no-store'});const json=await response.json() as {error?:{code:number};data?:{id:string;display_phone_number:string;name:string;language:string;status:string;components:{type:string;text?:string}[]}[];messages?:{id:string}[]};if(!response.ok)throw new ApiError(502,json.error?.code===190?'Your WhatsApp authorization expired. Please reconnect.':'Meta could not complete this request. Check your connection and permissions.');return json;}
export async function templates(userId:string):Promise<Template[]>{const c=connection(userId);if(!c)return [];const result=await meta(`${encodeURIComponent(c.wabaId)}/message_templates?fields=name,status,language,components&limit=100`,decrypt(c.token));return (result.data||[]).filter((t:{status:string})=>t.status==='APPROVED').map((t:{name:string;language:string;status:string;components:{type:string;text?:string}[]})=>{const body=t.components.find(x=>x.type==='BODY')?.text||'';return {name:t.name,language:t.language,status:t.status,body,parameters:new Set(body.match(/\{\{\d+\}\}/g)||[]).size,supported:!(/\{\{[^0-9]/.test(body))&&!t.components.some(x=>x.type==='HEADER'&&(!x.text||/\{\{/.test(x.text)))&&!t.components.some(x=>x.type==='BUTTONS')};}).filter((t:{supported:boolean})=>t.supported);}
