'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
type Client={id:string;business:string;name:string};
async function request<T=unknown>(path:string,data?:unknown){const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,cache:'no-store'});const result=await r.json() as T & {error?:string};if(!r.ok)throw new Error(result.error||'Could not connect.');return result;}
export function AdminTestWhatsApp(){
 const [available,setAvailable]=useState(false),[clients,setClients]=useState<Client[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{let active=true;request<{available:boolean}>('admin/test-whatsapp').then(async d=>{if(!d.available)return;const c=await request<{clients:Client[]}>('admin/clients');if(active){setClients(c.clients);setAvailable(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setSaved(false);try{await request('admin/test-whatsapp',Object.fromEntries(new FormData(form)));form.reset();setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!available)return error?<p className="error-box" role="alert">{error}</p>:null;
 return <section className="panel form-panel"><span className="eyebrow">LOCAL TESTING · SUPERADMIN ONLY</span><h2>Test WhatsApp inside your portal</h2><p>Assign Meta’s test number to one workspace. Then send messages from Leads and receive replies in Conversations.</p><form className="form-panel" onSubmit={submit}><label>Workspace<select name="userId" required defaultValue=""><option value="" disabled>Choose your test workspace</option>{clients.map(c=><option value={c.id} key={c.id}>{c.business} — {c.name}</option>)}</select></label><label>WhatsApp Business Account ID<input name="wabaId" required inputMode="numeric" pattern="[0-9]+" defaultValue="1468109601694352"/></label><label>Test phone number ID<input name="phoneId" required inputMode="numeric" pattern="[0-9]+" defaultValue="1027882580408674"/></label><label>Test access token<input name="token" type="password" required autoComplete="off" maxLength={4000} placeholder="Paste the token from Meta’s Try it out page"/></label><p>The token is encrypted on this server and used to verify the number and subscribe this app to incoming messages. A temporary token must be replaced here when it expires. This will not replace a different number already connected to the workspace.</p><button className="btn primary" disabled={busy}>{busy?'Verifying and connecting…':'Connect test number to workspace'}</button>{error&&<p className="error-box" role="alert">{error}</p>}{saved&&<div role="status" className="info-banner"><div><strong>Test number connected.</strong><p>Sign in to the selected workspace. Add your verified recipient as a lead with permission, then choose Start chat. Only recipients verified in Meta can receive test-number messages.</p><Link href="/leads">Open workspace leads →</Link></div></div>}</form></section>;
}
