'use client';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,MessageCircle,Users,Check,BookOpen,Layers,ChevronRight,Sparkles} from 'lucide-react';
export function Landing(){
return <div className="marketing"><nav className="marketing-nav"><Link href="/" className="marketing-brand" aria-label="Our Own Leads home"><span><MessageCircle size={23}/></span>Our Own Leads<span className="mint-dot">.</span></Link><div className="marketing-links"><a href="#features">Why Our Own Leads</a><a href="#how-it-works">How it works</a></div><div className="marketing-actions"><Link href="/login">Log in</Link><Link className="marketing-cta" href="/signup">Get started <ArrowUpRight size={16}/></Link></div></nav>
<section className="marketing-hero"><div className="hero-copy"><span className="marketing-kicker"><span/> BUILT FOR BUSINESSES. MADE FOR PEOPLE.</span><h1>Your leads.<br/>Your conversations.<br/><em>Your next big win.</em></h1><p>A simpler home for your customer relationships. Bring your leads together, follow up on WhatsApp, and turn everyday conversations into business opportunities.</p><div className="hero-buttons"><Link className="marketing-cta" href="/signup">Create your workspace <ArrowRight size={19}/></Link><a href="#how-it-works">See how it works <ChevronRight size={17}/></a></div><div className="hero-benefits"><span><Check size={15}/> Your business number</span><span><Check size={15}/> Your customer relationships</span></div></div>
<div className="hero-product" aria-label="Illustrative preview of the Our Own Leads workspace"><div className="preview-window"><div className="preview-bar"><span/><span/><span/><small>YOUR BUSINESS, CONNECTED</small></div><div className="preview-body"><aside><div className="preview-logo"><MessageCircle size={19}/></div><Layers size={18}/><Users size={18}/><MessageCircle size={18}/><BookOpen size={18}/></aside><div className="preview-content"><div className="preview-heading"><div><small>GOOD THINGS START WITH A HELLO</small><h3>Your next opportunity.</h3></div><span className="preview-add">+ Add lead</span></div><div className="preview-stats"><div><small>Your leads</small><strong>128 <span>↗</span></strong></div><div><small>In conversation</small><strong>36 <span>↗</span></strong></div><div><small>Customers won</small><strong>12 <span>↗</span></strong></div></div><div className="preview-table"><div className="preview-table-head"><strong>People. Not just numbers.</strong><small>View all →</small></div>{[['AK','Aarav Kumar','Northstar Studio','Qualified'],['PS','Priya Shah','Bloom Interiors','Contacted'],['RM','Rohan Mehta','Summit Consulting','New lead']].map(([initials,name,company,stage],i)=><div className="preview-lead" key={name}><span className={'preview-person person-'+i}>{initials}</span><div><strong>{name}</strong><small>{company}</small></div><span className={'preview-stage stage-'+i}>{stage}</span></div>)}</div><small className="preview-disclaimer">Illustrative workspace · sample data</small></div></div></div><div className="preview-message"><span className="preview-whatsapp"><MessageCircle size={24}/></span><div><small>A CONVERSATION WORTH HAVING</small><strong>“Thanks! Let’s discuss the proposal.”</strong><p>One hello closer to your next customer.</p></div><span className="message-check">✓✓</span></div><div className="hero-orbit"/></div></section>
<div className="business-strip"><span>FOR THE BUSINESSES BUILDING WHAT’S NEXT</span><div>Agencies <i/> Consultants <i/> Service businesses <i/> Growing sales teams</div></div>
<section id="features" className="marketing-section"><div className="section-intro"><span className="marketing-kicker">LESS JUGGLING. MORE CONNECTING.</span><h2>From scattered leads<br/>to stronger relationships.</h2><p>Give every enquiry a place to belong—and your business a clear next step.</p></div><div className="feature-grid">{[[Users,'Every lead, in one place.','Bring in your contacts from CSV, Google Sheets, or a simple form. Keep names, notes, and next steps together.','01'],[MessageCircle,'Make your next hello count.','Start a WhatsApp conversation from a lead’s profile using your connected number and approved message templates.','02'],[BookOpen,'Your business knows best.','Build a shared library of services, pricing, and FAQs. Keep useful answers close to every conversation.','03']].map(([Icon,title,copy,n])=>{const I=Icon as typeof Users;return <article key={String(n)}><div className="feature-top"><span><I size={25}/></span><small>{String(n)}</small></div><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section>
<section id="how-it-works" className="marketing-how"><div><span className="marketing-kicker">A LITTLE SETUP. A LOT OF POSSIBILITY.</span><h2>A workspace that<br/>works the way you do.</h2><p>Start with the essentials. Build your relationships from there.</p><Link className="marketing-cta" href="/signup">Let’s get you started <ArrowRight size={18}/></Link></div><ol>{[['Make it yours','Add your business name, logo, and a little of your personality.'],['Bring your leads','Import your list, review the details, and choose who to follow up with.'],['Keep the conversation going','Connect WhatsApp, record messaging permission, and send your first approved introduction.']].map(([title,copy],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></section>
<section className="marketing-bottom"><span><Sparkles size={24}/> SMALL CONVERSATIONS. REAL POSSIBILITIES.</span><h2>Your next customer<br/>starts with a connection.</h2><Link className="marketing-cta" href="/signup">Make room for your next lead <ArrowRight size={19}/></Link><p>Local beta · AI-generated replies and guided Meta onboarding are coming next.</p></section><footer className="marketing-footer"><Link href="/" className="marketing-brand" aria-label="Our Own Leads home"><MessageCircle size={22}/> Our Own Leads<span className="mint-dot">.</span></Link><p>Built for growing businesses. Designed around people.</p><span>© {new Date().getFullYear()} Our Own Leads</span></footer></div>;
}
